# Import Library

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)

# Read Data

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/marufmuhtarif/dataset/refs/heads/main/netflix_titles.csv")
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...

# Info Data

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8807 entries, 0 to 8806
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   show_id       8807 non-null   object
 1   type          8807 non-null   object
 2   title         8807 non-null   object
 3   director      6173 non-null   object
 4   cast          7982 non-null   object
 5   country       7976 non-null   object
 6   date_added    8797 non-null   object
 7   release_year  8807 non-null   int64
 8   rating        8803 non-null   object
 9   duration      8804 non-null   object
 10  listed_in     8807 non-null   object
 11  description   8807 non-null   object
dtypes: int64(1), object(11)
memory usage: 825.8+ KB

# Describe Data

In [ ]:
df.describe()

       release_year
count   8807.000000
mean    2014.180198
std        8.819312
min     1925.000000
25%     2013.000000
50%     2017.000000
75%     2019.000000
max     2021.000000

# Cek Missing Value

In [ ]:
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

# Cek Duplikat

In [ ]:
df.duplicated().sum()

np.int64(0)

# Isi Missing Value

In [ ]:
# isi missing value country
df['country'] = df['country'].fillna(df['country'].mode()[0])

In [ ]:
# isi missing value rating
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [ ]:
# isi missing value duration
df['duration'] = df['duration'].fillna(df['duration'].mode()[0])

In [ ]:
# isi missing value date_added
df['date_added'] = df['date_added'].fillna(df['date_added'].mode()[0])

In [ ]:
# cek missing value
df.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country            0
date_added         0
release_year       0
rating             0
duration           0
listed_in          0
description        0
dtype: int64

# Ubah date_added menjadi format tanggal

In [ ]:
# Hapus spasi kosong
df['date_added'] = df['date_added'].str.strip()

In [ ]:
# Ubah ke datetime
df['date_added'] = pd.to_datetime(df['date_added'])

In [ ]:
#tambah kolom baru untuk year_added
df['year_added'] = df['date_added'].dt.year

In [ ]:
#ganti tipe data year_added ke int
df['year_added'] = df['year_added'].astype(int)

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,United States,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021

# Mengelompokkan rating

In [ ]:
# cek data uniq di rating
df['rating'].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', '74 min', '84 min', '66 min', 'NR',
       'TV-Y7-FV', 'UR'], dtype=object)

In [ ]:
# ubah data error menjadi nan
df.loc[df['rating'].str.contains('min', na=False), 'rating'] = None

In [ ]:
# isi missing value rating
df['rating'] = df['rating'].fillna(df['rating'].mode()[0])

In [ ]:
def rating_group(rating):
    if rating in ['TV-MA', 'R', 'NC-17']:
        return 'Adult'
    elif rating in ['PG-13', 'PG', 'TV-PG', 'TV-14']:
        return 'Teens'
    elif rating in ['TV-Y7', 'TV-Y', 'TV-Y7-FV']:
        return 'Children'
    else:
        return 'General'

In [ ]:
# buat kolom rating_group
df['rating_group'] = df['rating'].apply(rating_group)

In [ ]:
df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,year_added,rating_group
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,2021-09-25,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",2021,Teens
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",2021,Adult
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",United States,2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,2021,Adult
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,United States,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",2021,Adult
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,2021,Adult

# Membersihkan kolom country

In [ ]:
# hapus spasi dan koma
df['country'] = df['country'].str.strip()

In [ ]:
# pisahkan negara
df['country'] = df['country'].str.split(', ')

In [ ]:
# explode negara
df = df.explode('country')

In [ ]:
# hapus spasi
df['country'] = df['country'].str.strip()

# Insight

## Distribusi jenis konten

In [ ]:
df['type'].value_counts()

type
Movie      7814
TV Show    3031
Name: count, dtype: int64

## Negara produsen konten terbanyak di neftlix

In [82]:
df.groupby('type')['country'].value_counts().head()

type   country
Movie  United States     3191
       India              962
       United Kingdom     532
       Canada             319
       France             303
Name: count, dtype: int64

## Rating konten antar negara produksi

In [85]:
# df.groupby('country')['rating_group'].value_counts().head(10)
df.groupby('type')['year_added'].value_counts()

type     year_added
Movie    2019          1773
         2020          1649
         2018          1566
         2021          1272
         2017          1091
         2016           334
         2015            73
         2014            25
         2011            17
         2013             6
         2012             4
         2009             2
         2008             1
         2010             1
TV Show  2020           697
         2019           647
         2021           558
         2018           472
         2017           383
         2016           224
         2015            33
         2014             9
         2013             7
         2008             1
Name: count, dtype: int64

## Genre konten netflix

In [ ]:
df['listed_in'].value_counts().head()

listed_in
Dramas, International Movies                        485
Documentaries                                       423
Dramas, Independent Movies, International Movies    393
Stand-Up Comedy                                     335
Comedies, Dramas, International Movies              314
Name: count, dtype: int64

## Distribusi kelompok usia

In [ ]:
df['rating_group'].value_counts().head()

rating_group
Adult       4999
Teens       4605
Children     821
General      420
Name: count, dtype: int64

## Pertumbuhan konten berdasar tahun rilis

In [ ]:
df[['type','release_year']].value_counts().head()

type   release_year
Movie  2017            974
       2018            963
       2016            878
       2019            763
       2020            564
Name: count, dtype: int64

## Pertumbuhan konten netflik per tahun

In [ ]:
df[['year_added']].value_counts()

year_added
2019          2420
2020          2346
2018          2038
2021          1830
2017          1474
2016           558
2015           106
2014            34
2011            17
2013            13
2012             4
2008             2
2009             2
2010             1
Name: count, dtype: int64

In [ ]:
df['rating_group'].value_counts()

rating_group
Adult       4999
Teens       4605
Children     821
General      420
Name: count, dtype: int64

In [ ]:
pip install sqlalchemy psycopg2-binary

Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl.metadata (4.9 kB)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.12-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl (4.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 88.5 MB/s eta 0:00:00
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.9.12

In [ ]:
import pandas as pd

In [ ]:
from sqlalchemy import create_engine

In [ ]:
DATABASE_URL = (
"postgresql://postgres.yjgdyyxtpvcligtseidk:iF#vKZ3xR7.S*Vh@aws-1-ap-south-1.pooler.supabase.com:6543/postgres"
)

engine = create_engine(DATABASE_URL)

In [ ]:
df.to_sql("netflix_titles",engine,if_exists="replace",index=False)

845

##